### ISSUE TITLE
Failure to populate in latest tcadmin verison

### ISSUE THREAD

**Issue by Ireheart** [Alexr03/TCAdminCustomMods#5]
Tried this, fails to populate with mods for uMod on Rust, perhaps i am missing something but unsure.

**Comment by Alexr03** [comment]
Hi,
Update TCAdmin to 2.0.160.2 and try again.

**Comment by Alexr03** [comment]
Did you try the above ^

**Comment by Psychoboy** [comment]
I am not the one that originally posted this issue, but updating it that version (Even though not officially released) fixed it.
